name: futureUsandoApi
description: Um projeto Flutter para demonstrar o uso de Future com API.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true